### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by XefPatterson** [cr7anand/neural_temporal_models#3]
Hi, given the restrictive default copyrights of an unlicensed github repo ("_no one may reproduce, distribute, or create derivative works from your work._"), is there any hope that this repo gets a more open license eventually? Mostly thinking about the NPSS code that people could use and share.

Info:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Thanks!

**Comment by AnkurMali** [comment]
Thank you we have added license to our repository. You can use our work to reproduce results or even create multiple derivative works from this repo.
